name: Messe Eventkalender Worker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scrape-messe:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Playwright installieren
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium

      - name: Messe scrapen
        run: |
          node worker/messe_scraper.js || echo "Messe-Scraper fehlgeschlagen"

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/events_messe.json
          git commit -m "Update Messe Events" || echo "Keine Änderungen"
          git push

      - name: Arena scrapen
        run: |
          node worker/arena_scraper.js|| echo "Arena-Scraper fehlgeschlagen"

      - name: Arena Events committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/events_arena.json
          git commit -m "Update Arena Events" || echo "Keine Änderungen"
          git push

      - name: RB Leipzig Heimspiele scrapen
        run: node worker/rb_scraper.js || echo "RB-Scraper fehlgeschlagen"
      
      - name: RB Leipzig Events committen
        run: |
          git add data/events_rb.json
          git commit -m "Update RB Leipzig Heimspiele" || echo "Keine Änderungen"
          git push    

      - name: Stadt Leipzig Events scrapen
        run: node worker/stadt_scraper.js || echo "Stadt-Scraper fehlgeschlagen"

      - name: Stadt Leipzig Events committen
        run: |
          git add data/events_stadt.json
          git commit -m "Update Stadt Leipzig Events" || echo "Keine Änderungen"
          git push          

      - name: Feiertage laden (DE-SN)
        run: node worker/holiday_scraper.js || echo "Feiertage-Scraper fehlgeschlagen"
    
      - name: Feiertage committen
        run: |
          git add data/holidays_sn_*.json
          git commit -m "Update Feiertage DE-SN" || echo "Keine Änderungen"
          git push

      - name: Magdeburg Messe Events scrapen
        run: node worker/magdeburg_messe.js || echo "Magdeburg Messe Scraper fehlgeschlagen"
      
      - name: Magdeburg Messe Events committen
        run: |
          git add data/events_magdeburg_messe.json
          git commit -m "Update Messe Magdeburg Events" || echo "Keine Änderungen"
          git push       
